# Number of days of inactivity before an issue becomes stale
daysUntilStale: 30
# Number of days of inactivity before a stale issue is closed
daysUntilClose: 7
# Issues with these labels will never be considered stale
exemptLabels:
  - in progress
  - enhancement
  - new target
# Label to use when marking an issue as stale
staleLabel: stale
# Comment to post when marking an issue as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity In 30 Days. It will be closed if no further activity occurs In 7 Days. 
  Please Retest on latest version and if issue still persist comment on This issue
# Comment to post when closing a stale issue. Set to `false` to disable
closeComment: false
